SimStore_DucPham/ViewModels/BillViewModel.cs
using SimStore_DucPham.Models;
using System;
using System.Collections.Generic;

namespace SimStore_DucPham.ViewModels
{
    public class BillViewModel
    {
        public string Id { get; set; }
        public string ProductNumbers { get; set; }
        public string CreateTime { get; set; }
        public DateTime CreateDateTime { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public string CreatePhoneNumber { get; set; }
        public string Status { get; set; }
        public long SumMoney { get; set; }
        public string UpdateUserId { get; set; }
        public string UpdateTime { get; set; }
        public bool IsPay { get; set; }
        public string Note { get; set; }
        public string ReasonCanceled { get; set; }
        public bool IsOnline { get; set; }
        public string AddressOrderId { get; set; }
        public string Code { get; set; }
        public AddressOrderViewModel AddressOrder { get; set; }
        public List<DetailBillViewModel> DetailBills { get; set; }
    }

    public class DetailBillViewModel
    {
        public string Id { get; set; }
        public string BillId { get; set; }
        public string ProductId { get; set; }
        public string ProductNumber { get; set; }
        public long ProductPrice { get; set; }
        public string ProductCarrierId { get; set; }
        public string ProductCarrierName { get; set; }
        public string ProductCarrierImage { get; set; }
        public string ProductCreateTime { get; set; }
        public string ProductDescription { get; set; }
        public string ProductCategoryId { get; set; }
        public string ProductCategoryName { get; set; }
    }

    public class AddressOrderViewModel : AddressOrderModel
    {
        public string CreateName { get; set; }
        public string AddressFull { get; set; }
    }
}

SimStore_DucPham/ViewModels/ProductViewModel.cs
namespace SimStore_DucPham.ViewModels
{
    public class ProductViewModel
    {
        public string Id { get; set; }
        public string Number { get; set; }
        public string CarrierId { get; set; }
        public string CarrierName { get; set; }
        public string CarrierImage { get; set; }
        public long Price { get; set; }
        public string CreateTime { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public string Description { get; set; }
        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
        public long Sale { get; set; }
        public bool IsSell { get; set; }
        public bool IsActive { get; set; }
    }
}

SimStore_DucPham/ViewModels/UserViewModel.cs
namespace SimStore_DucPham.ViewModels
{
    public class UserViewModel
    {
        public string Id { get; set; }
        public string FullName { get; set; }
        public string Avatar { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public string CreateTime { get; set; }
        public bool IsActive { get; set; }
        public bool IsLock { get; set; }
        public string RoleId { get; set; }
    }
}

SimStore_DucPham/Controllers/AdminManagerController.cs
using Newtonsoft.Json;
using SimStore_DucPham.Data;
using SimStore_DucPham.Filter;
using SimStore_DucPham.Helper;
using SimStore_DucPham.Models;
using SimStore_DucPham.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimStore_DucPham.Controllers
{
    //[AuthFilterAdmin]
    //[SessionExpireFilterAdmin]
    //[Authorize(Roles = "Administrator")]
    public class AdminManagerController : Controller
    {
        #region Data

        private RoleData roleData = new RoleData();
        private UserData userData = new UserData();
        private UserRoleData userRoleData = new UserRoleData();
        private CategoryData categoryData = new CategoryData();
        private CarrierData carrierData = new CarrierData();
        private ProductData productData = new ProductData();
        private StatisticsData statisticsData = new StatisticsData();
        private BillData billData = new BillData();

        #endregion Data

        #region Statistics

        // GET: AdminManager
        public ActionResult Index()
        {
            return View();
        }

        #endregion Statistics

        #region Role Manager

        // GET: RoleManager
        public ActionResult Role()
        {
            return View();
        }

        public JsonResult GetAllRole()
        {
            List<RoleModel> roles = roleData.GetAllRole();
            return Json(new { data = roles }, JsonRequestBehavior.AllowGet);
        }

        #endregion Role Manager

        #region User Manager

        // GET: UserManager
        public ActionResult User()
        {
            return View();
        }

        public JsonResult GetAllUser()
        {
            List<UserViewModel> users = userData.GetAllUser();
            return Json(new { data = users }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetInfoUser(string userId)
        {
            UserViewModel user = userData.GetInfoUser(userId ?? "");
            return Json(new { data = user }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ChangeUserToAdmin(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return Json(new { data = new ResultModel() { Status = false, Message = "UserId không được rỗng" } });
            }
            return Json(new { data = userRoleData.ChangeUserToAdmin(userId) });
        }

        [HttpPost]
        public JsonResult ChangeUserToCustomer(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return Json(new { data = new ResultModel() { Status = false, Message = "UserId không được rỗng" } });
            }
            ApplicationUser user = (ApplicationUser)Session[KeyHelper.Session_Login];
            if (user.Id.Equals(userId))
            {
                return Json(new { data = new ResultModel() { Status = false, Message = "Bạn đang dùng tài khoản này. Không thể thực hiện yêu cầu này." } });
            }
            return Json(new { data = userRoleData.ChangeUserToCustomer(userId) });
        }

        [HttpPost]
        public JsonResult LockUser(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return Json(new { data = new ResultModel() { Status = false, Message = "UserId không được rỗng" } });
            }
            ApplicationUser user = (ApplicationUser)Session[KeyHelper.Session_Login];
            if (user.Id.Equals(userId))
            {
                return Json(new { data = new ResultModel() { Status = false, Message = "Bạn đang dùng tài khoản này. Không thể thực hiện yêu cầu này." } });
            }
            return Json(new { data = userData.LockUser(userId) });
        }

        [HttpPost]
        public JsonResult UnLockUser(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return Json(new { data = new ResultModel() { Status = false, Message = "UserId không được rỗng" } });
            }
            return Json(new { data = userData.UnLockUser(userId) });
        }

        [HttpPost]
        public JsonResult UpdateProfile(string userId, string fullName, string email, string phoneNumber, string address)
        {
            if (string.IsNullOrEmpty(userId))
            {
                return Json(new { data = new ResultModel() { Status = false, Message = "UserId không được rỗng" } });
            }
            ResultModel result = userData.UpdateProfile(userId, fullName ?? "", email ?? "", phoneNumber ?? "", address ?? "");
            return Json(new { data = result });
        }

        #endregion User Manager

        #region Category Manager

        public ActionResult Category()
        {
            return View();
        }

        public JsonResult GetAllCategory()
        {
            List<CategoryModel> categories = categoryData.GetAllCategory();
            return Json(new { data = categories }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetInfoCategory(string categoryId)
        {
            CategoryModel category = categoryData.GetInfoCategory(categoryId ?? "");
            return Json(new { data = category }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult IsActiveCategory(string categoryId, bool isActive)
        {
            ResultModel result = categoryData.IsActiveCategory(categoryId, isActive);
            return Json(new { data = result });
        }

        [HttpPost]
        public JsonResult DeleteCategory(string categoryId)
        {
            ResultModel result = categoryData.DeleteCategory(categoryId);
            return Json(new { data = result });
        }

        [HttpPost]
        public JsonResult UpdateCategory(string categoryId, string categoryName, string categoryDescription)
        {
            ResultModel result = categoryData.UpdateCategory(categoryId, categoryName, categoryDescription);
            return Json(new { data = result });
        }

        [HttpPost]
        public JsonResult CreateCategory(string categoryStr)
        {
            CategoryModel category = JsonConvert.DeserializeObject<CategoryModel>(categoryStr);
            category.Id = category.Name.ToLower().Replace(' ', '-');
            category.Description = category.Description ?? "";
            ResultModel result = categoryData.CreateCategory(category);
            return Json(new { data = result });
        }

        #endregion Category Manager

        #region Carrier Manager

        public ActionResult Carrier()
        {
            return View();
        }

        public JsonResult GetAllCarrier()
        {
            List<CarrierModel> carriers = carrierData.GetAllCarrier();
            return Json(new { data = carriers }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetInfoCarrier(string carrierId)
        {
            CarrierModel carrier = carrierData.GetInfoCarrier(carrierId);
            return Json(new { data = carrier }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult IsActiveCarrier(string carrierId, bool isActive)
        {
            ResultModel result = carrierData.IsActiveCarrier(carrierId, isActive);
            return Json(new { data = result });
        }

        [HttpPost]
        public JsonResult DeleteCarrier(string carrierId)
        {
            ResultModel result = carrierData.DeleteCarrier(carrierId);
            return Json(new { data = result });
        }

        [HttpPost]
        public JsonResult UpdateCarrier(string carrierId, string carrierName, string carrierDescription, string carrierImage)
        {
            ResultModel result = carrierData.UpdateCarrier(carrierId, carrierName, carrierDescription, carrierImage);
            return Json(new { data = result });
        }

        [HttpPost]
        public JsonResult CreateCarrier(string carrierStr)
        {
            CarrierModel carrier = JsonConvert.DeserializeObject<CarrierModel>(carrierStr);
            carrier.Id = carrier.Name.ToLower().Replace(' ', '-');
            carrier.Description = carrier.Description ?? "";
            ResultModel result = carrierData.CreateCarrier(carrier);
            return Json(new { data = result });
        }

        #endregion Carrier Manager

        #region Product Manager

        public ActionResult Product()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetAllProduct(string status, string carrier, string price, string sapxep)
        {
            List<ProductViewModel> products = productData.GetAllProduct().OrderByDescending(p => p.CreateTime).ToList();
            if (!string.IsNullOrEmpty(status))
            {
                if (!status.Equals("all"))
                {
                    if (status.Equals("sell"))
                    {
                        products = products.Where(p => p.IsSell).ToList();
                    }
                    else if (status.Equals("nosell"))
                    {
                        products = products.Where(p => !p.IsSell).ToList();
                    }
                    else if (status.Equals("active"))
                    {
                        products = products.Where(p => p.IsActive).ToList();
                    }
                    else
                    {
                        products = products.Where(p => !p.IsActive).ToList();
                    }
                }
            }
            if (!string.IsNullOrEmpty(carrier))
            {
                if (!carrier.Equals("all"))
                {
                    products = products.Where(p => p.CarrierId.Equals(carrier)).ToList();
                }
            }
            if (!string.IsNullOrEmpty(price))
            {
                if (!price.Equals("all"))
                {

SimStore_DucPham/Views/AdminManager/Bill.cshtml
@{
    ViewBag.Title = "Quản lý đơn hàng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<style>
    td.details-control {
        background: url('/Plugins/datatables/details_open.png') no-repeat right;
        cursor: pointer;
        /*padding-left: 25px !important;*/
    }

    tr.shown td.details-control {
        background: url('/Plugins/datatables/details_close.png') no-repeat right;
        /*padding-left: 25px !important;*/
        cursor: pointer;
    }

    #iGiaoHang tr th, #iGiaoHang tr td, #iDonHang tr th, #iDonHang tr td, #tDonHang tr th, #tDonHang tr td {
        border: 1px solid #3a3434;
    }

    .form-group {
        margin-bottom: 0px;
    }
</style>
<div class="modal fade" id="info-bill" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Chi tiết hóa đơn</h4>
            </div>
            <div class="modal-body" style="margin: 0px 15px;">
                <form id="frmUpdate" class="form-horizontal">
                    <div class="row line-row">
                        <div class="col-md-6" style="padding-left: 0px;">
                            <div class="form-inline">
                                <label>Loại đơn hàng: <span id="iLoaiDonHang" style='font-weight: bold;'></span></label>
                                <input type="hidden" id="iBillId" />
                            </div>
                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-5" style="padding-left: 0px;">
                            <div class="form-inline">
                                <label>Trạng thái: <span id="iTrangThai" style='font-weight: bold;'></span></label>
                            </div>
                        </div>
                    </div>
                    <div class="row line-row">
                        <div class="col-md-6" style="padding-left: 0px;">
                            <div class="form-inline">
                                <label>Người mua: <span id="iNguoiDat" style='font-weight: bold;'></span></label>
                            </div>
                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-5" style="padding-left: 0px;" id="shDienThoai">
                            <div class="form-inline">
                                <label>Điện thoại: <span id="iDienThoai" style='font-weight: bold;'></span></label>
                            </div>
                        </div>
                    </div>
                    <div class="row line-row">
                        <div class="col-md-6" style="padding-left: 0px;">
                            <div class="form-inline">
                                <label>Thời gian mua: <span id="iThoiGianDat" style='font-weight: bold;'></span></label>
                            </div>
                        </div>
                        <div class="col-md-1"></div>
                        <div class="col-md-5" style="padding-left: 0px;">
                            <div class="form-inline">
                                <label>Thanh toán: <span id="iThanhToan" style='font-weight: bold;'></span></label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Thông tin giao hàng</label>
                                <table class="table table-bordered table-responsive" id="iGiaoHang">
                                    <tr>
                                        <th style="width: 120px;">Người nhận:</th>
                                        <td id="iNguoiNhan">Phạm Minh Đức</td>
                                    </tr>
                                    <tr>
                                        <th style="width: 120px;">Điện thoại:</th>
                                        <td id="iDienThoaiNhan">Phạm Minh Đức</td>
                                    </tr>
                                    <tr>
                                        <th style="width: 120px;">Địa chỉ:</th>
                                        <td id="iDiaChiNhan">Phạm Minh Đức</td>
                                    </tr>
                                    <tr>
                                        <th style="width: 120px;">Ghi chú:</th>
                                        <td id="iGhiChu">Phạm Minh Đức</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label style="display: unset;">Thông tin đơn hàng <span class="f-right">Tổng tiền: <strong id="iTongTien">159000</strong></span></label>
                                <table class="table table-bordered table-responsive" style="margin-top: 10px;">
                                    <thead id="tDonHang">
                                        <tr>
                                            <th>Số Sim</th>
                                            <th>Mạng</th>
                                            <th>Giá bán</th>
                                            <th>Danh mục</th>
                                        </tr>
                                    </thead>
                                    <tbody id="iDonHang">
                                        <tr>
                                            <td>0764545304</td>
                                            <td>Mobifone</td>
                                            <td>159000</td>
                                            <td>Chưa phân loại</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer" id="listBtn">
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div class="bg-color-white box">
    <h2>Danh sách đơn hàng</h2>
    <div class="row" style="margin-bottom: 10px;">
        <div class="col-md-3" style="padding-left: 20px;">
            <div class="form-inline">
                <label>Trạng thái:</label>
                <select class="form-control" id="select-status" style="height: 31px;">
                    <option value="all">Tất cả</option>
                    <option value="Đợi xác nhận mail">Đợi xác nhận mail</option>
                    <option value="Đợi xác nhận">Đợi xác nhận</option>
                    <option value="Đã xác nhận">Đã xác nhận</option>
                    <option value="Đang giao hàng">Đang giao hàng</option>
                    <option value="Đã giao hàng">Đã giao hàng</option>
                    <option value="Hủy bỏ">Hủy bỏ</option>
                </select>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-inline">
                <label>Hình thức mua:</label>
                <select class="form-control" id="select-isonline" style="height: 31px;">
                    <option value="all">Tất cả</option>
                    <option value="online">Mua Online</option>
                    <option value="offline">Mua tại quầy</option>
                </select>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-inline">
                <label>Thanh toán:</label>
                <select class="form-control" id="select-ispay" style="height: 31px;">
                    <option value="all">Tất cả</option>
                    <option value="dathanhtoan">Đã thanh toán</option>
                    <option value="chuathanhtoan">Chưa thanh toán</option>
                </select>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-inline f-right">
                <label>Thời gian:</label>
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" class="form-control pull-right" id="reservation">
                    <input type="hidden" id="timeCheck" />
                </div>
            </div>
        </div>
    </div>
    <table id="bill-table" class="table table-responsive table-bordered table-hover">
        <thead>
            <tr>
                <th>STT</th>
                <th>Sim mua</th>
                <th class="text-center">Tổng tiền</th>
                <th>Thời gian</th>
                <th>Hình thức</th>
                <th>Trạng thái</th>
                <th>Thao tác</th>
            </tr>
        </thead>
    </table>
</div>
@section Scripts {
    <script src="~/Scripts/Administrator/billJS.js"></script>
}

SimStore_DucPham/Views/AdminManager/Carrier.cshtml
@{
    ViewBag.Title = "Quản lý nhà mạng";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="modal fade" id="modal-carrier" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Thêm nhà mạng mới</h4>
            </div>
            <div class="modal-body" style="margin: 0px 15px;">
                <form id="frmUpdate" class="form-horizontal">
                    <input type="hidden" id="iId" />
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Tên nhà mạng</label>
                                <input type="text" class="form-control" id="iName" value="" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea rows="4" class="form-control" id="iDescription"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Trạng thái</label>
                                <input id="iIsActive" type="checkbox" checked style="margin-left: 5px;" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Hình ảnh</label>
                                <input id="image-base" type="hidden" />
                                <div class="avatar-upload">
                                    <div class="avatar-edit">
                                        <input type='file' id="imageUpload" accept=".png, .jpg, .jpeg" />
                                        <label for="imageUpload"></label>
                                    </div>
                                    <div class="avatar-preview">
                                        <div id="imagePreview" style="background-image: url(/Content/Images/logo-nha-mang/no-image-carrier.png);">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-primary" id="add-carrier">Thêm</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div class="modal fade" id="carrier-info">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Chi tiết nhà mạng</h4>
            </div>
            <div class="modal-body" style="margin: 0px 15px;">
                <form id="frmUpdate" class="form-horizontal">
                    <input type="hidden" id="pId" />
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Tên nhà mạng</label>
                                <input type="text" class="form-control" id="pName" value="" />
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Mô tả</label>
                                <textarea type="text" rows="4" class="form-control" id="pDescription"></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Hình ảnh</label>
                                <input id="image-base-2" type="hidden" />
                                <div class="avatar-upload">
                                    <div class="avatar-edit">
                                        <input type='file' id="imageUpload2" accept=".png, .jpg, .jpeg" />
                                        <label for="imageUpload2"></label>
                                    </div>
                                    <div class="avatar-preview">
                                        <div id="imagePreview2" style="background-image: url(/Content/Images/logo-nha-mang/no-image-carrier.png);">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" id="update-carrier" class="btn btn-primary f-right">Cập nhật</button>
                <button type="button" class="btn btn-default f-left" data-dismiss="modal">Đóng</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<div class="bg-color-white box">
    <h2>Danh sách nhà mạng</h2>
    <div class="row">
        <div class="col-xs-12" style="margin-bottom: 5px;">
            <button type="button" class="btn btn-primary btn-sm f-right" data-toggle="modal" data-target="#modal-carrier">
                <i class="fa fa-plus"></i> Thêm nhà mạng
            </button>
        </div>
    </div>
    <table id="carrier-table" class="table table-responsive table-bordered table-hover">
        <thead>
            <tr>
                <td>STT</td>
                <td>Tên nhà mạng</td>
                <td>Hình ảnh</td>
                <td>Mô tả</td>
                <td>Trạng thái</td>
                <td class="text-center">Thao tác</td>
            </tr>
        </thead>
    </table>
</div>
@section Scripts {
    <script src="~/Scripts/Administrator/carrierJS.js"></script>
}

SimStore_DucPham/Views/AdminManager/Index.cshtml
@{
    ViewBag.Title = "Biểu đồ sơ lượt";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@{ Html.RenderAction("DefaultStatistics", "AdminManager");}

SimStore_DucPham/Views/AdminManager/Role.cshtml
@{
    ViewBag.Title = "Danh sách quyền";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="bg-color-white box">
    <h2>Danh sách các quyền</h2>
    <table class="table table-responsive table-bordered">
        <thead>
            <tr>
                <th style="width: 35px;" class="text-center">STT</th>
                <th>Tên quyền</th>
            </tr>
        </thead>
        <tbody id="content-table"></tbody>
    </table>
</div>
@section Scripts {
    <script src="~/Scripts/Administrator/roleJS.js"></script>
}